### PR TITLE
added bandlab specific release url

### PR DESCRIPTION
**Pull request by iovorobiev**

### CODE REVIEW

**Comment by stepango** [comment]
Looks ok

**Comment by gildor** [comment]
@iovorobiev Let's add info about Bintray parameters to README.md

**Comment by gildor** [comment]
@iovorobiev Also let's replace `https://bintray.com/bandlab/maven/` with something like `https://bintray.com/{BINTRAY_LOGIN}/maven `

**Comment by gildor** [comment]
Ok

**Pull request merged**
